# Generated by Django 4.0.4 on 2022-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_key_banner', models.TextField(db_collation='utf8_unicode_ci', max_length=100)),
                ('ads_key_interstial', models.TextField(db_collation='utf8_unicode_ci', max_length=100)),
                ('ad_display_count', models.IntegerField()),
                ('ads_key_openads', models.TextField(db_collation='utf8_unicode_ci', max_length=100)),
                ('arr_trend', models.TextField(db_collation='utf8_unicode_ci', max_length=100)),
            ],
            options={
                'db_table': 'tbl_setting',
                'managed': False,
            },
        ),
    ]
