# Generated by Django 4.0.4 on 2022-05-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tblsetting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblsetting',
            table='tbl_setting_web',
        ),
    ]
