# Generated by Django 4.0.3 on 2022-06-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tblsettingweb_delete_tblsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblCategory',
        ),
        migrations.DeleteModel(
            name='TblComment',
        ),
        migrations.RemoveField(
            model_name='tblfav',
            name='vid',
        ),
        migrations.RemoveField(
            model_name='tblrating',
            name='vid',
        ),
        migrations.DeleteModel(
            name='TblReport',
        ),
        migrations.DeleteModel(
            name='TblSettingWeb',
        ),
        migrations.DeleteModel(
            name='TblUsers',
        ),
        migrations.DeleteModel(
            name='TblFav',
        ),
        migrations.DeleteModel(
            name='TblRating',
        ),
        migrations.DeleteModel(
            name='TblVideo',
        ),
    ]
